### ISSUE TITLE
SHortcode

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-boilerplate#221] opened 2020-09-01 16:25 UTC
How to add shortcode inside component
do_shortcode( '[mc4wp_form id="43"]' ); for example this not working

Thanks

**Comment by IvanGrginovInf** [comment] 2020-09-02 06:33
Closed because it's a duplicate of https://github.com/infinum/eightshift-libs/issues/79

**Closed by IvanGrginovInf** 2020-09-02 06:33 UTC
